import PavingToeplitzPositroids.Basic
import PavingToeplitzPositroids.MixedPlucker
import PavingToeplitzPositroids.SortedPlucker
import PavingToeplitzPositroids.Projection
import PavingToeplitzPositroids.ExactExample
import PavingToeplitzPositroids.IntervalSupport
import PavingToeplitzPositroids.ZeroRunExistence
import PavingToeplitzPositroids.HomogeneousBase
import PavingToeplitzPositroids.LocalInverse
import PavingToeplitzPositroids.Counting
import PavingToeplitzPositroids.PositiveExpansion
import PavingToeplitzPositroids.InterpolationAbstract
import PavingToeplitzPositroids.ModuleInterpolation
import PavingToeplitzPositroids.Interpolation
import PavingToeplitzPositroids.MatrixInterpolation
import PavingToeplitzPositroids.SubtractionFree
import PavingToeplitzPositroids.ConcreteExchange
import PavingToeplitzPositroids.Refinement
import PavingToeplitzPositroids.Circuits
import PavingToeplitzPositroids.Classification
import PavingToeplitzPositroids.PaperClassification
import PavingToeplitzPositroids.SupportTheorem
import PavingToeplitzPositroids.MatroidHyperplanes
import PavingToeplitzPositroids.IntervalFamily
import PavingToeplitzPositroids.LocalRealization
import PavingToeplitzPositroids.TriangularChart
import PavingToeplitzPositroids.TriangularLinear
import PavingToeplitzPositroids.TriangularJacobian
import PavingToeplitzPositroids.FiniteDifference
import PavingToeplitzPositroids.PolynomialChart
import PavingToeplitzPositroids.PolynomialBase
import PavingToeplitzPositroids.PascalKernel
import PavingToeplitzPositroids.PolynomialJacobian
import PavingToeplitzPositroids.DeterminantDerivative
import PavingToeplitzPositroids.GeneralizedVandermonde

/-!
# Positive consecutive-minor interpolation and paving Toeplitz positroids

This library formalizes *Positive Consecutive-Minor Interpolation and Paving
Toeplitz Positroids*.
-/
